/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_Window.java
 *
 * Created on Mar 11, 2014, 12:46:47 PM
 */
package gruppe9.kalender.frontend;

import java.util.Date;

import org.jdesktop.swingx.plaf.MonthViewUI;

import gruppe9.kalender.model.Meeting;

/**
 *
 * @author krake
 */
public class Edit_Avtale extends javax.swing.JFrame {
    private Main_Window main;
    /** Creates new form Main_Window 
     * @param meeting */
    Meeting meeting;
    public Edit_Avtale(Main_Window main, Meeting meeting) 
    {
    	setMeeting(meeting);
        this.main = main;
        initComponents();
    }
    private void setMeeting(Meeting meeting)
    {
    	if(meeting != null)
    	{
    		this.meeting = meeting; 
    		return;
    	}
    	else
    	{
    	}
    	
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAvtale = new javax.swing.JPanel();
        jLabelAvtale = new javax.swing.JLabel();
        jTextFieldAvtale = new javax.swing.JTextField();
        jLabelAvtaleBeskrivelse = new javax.swing.JLabel();
        jScrollPaneAvtale = new javax.swing.JScrollPane();
        jTextAreaAvtale = new javax.swing.JTextArea();
        jPanelDeltakere = new javax.swing.JPanel();
        jLabelDeltakere = new javax.swing.JLabel();
        jComboBoxDeltakerSok = new javax.swing.JComboBox();
        jButtonDeltakerLeggTil = new javax.swing.JButton();
        jButtonDeltakerFjern = new javax.swing.JButton();
        jScrollPaneDeltakere = new javax.swing.JScrollPane();
        jListDeltakere = new javax.swing.JList();
        jPanelDato = new javax.swing.JPanel();
        jXMonthViewDatovelger = new org.jdesktop.swingx.JXMonthView();
        jLabelDato = new javax.swing.JLabel();
        jTextFieldDato = new javax.swing.JTextField();
        jLabelDatoStart = new javax.swing.JLabel();
        jLabelDatoSlutt = new javax.swing.JLabel();
        jTextFieldDatoStart = new javax.swing.JTextField();
        jTextFieldDatoSlutt = new javax.swing.JTextField();
        jLabelVarighet = new javax.swing.JLabel();
        jTextFieldVarighet = new javax.swing.JTextField();
        jButtonNesteMnd = new javax.swing.JButton();
        jButtonForrigeMnd = new javax.swing.JButton();
        jButtonLagre = new javax.swing.JButton();
        jButtonAvbryt = new javax.swing.JButton();
        jPanelRom = new javax.swing.JPanel();
        jLabelRom = new javax.swing.JLabel();
        jTextFieldRom = new javax.swing.JTextField();
        jLabelVelgRom = new javax.swing.JLabel();
        jScrollPaneRom = new javax.swing.JScrollPane();
        jListRom = new javax.swing.JList();
        jRadioButtonRomAuto = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelAvtale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        this.jXMonthViewDatovelger.setDaysOfTheWeek(new String[]{"S","M","Ti","O","To","F","L"});
        jLabelAvtale.setText("Avtalenavn:");

        jTextFieldAvtale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldAvtaleAction(evt);
            }
        });

        jLabelAvtaleBeskrivelse.setText("Beskrivelse:");

        jScrollPaneAvtale.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneAvtale.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaAvtale.setColumns(20);
        jTextAreaAvtale.setRows(5);
        jScrollPaneAvtale.setViewportView(jTextAreaAvtale);

        javax.swing.GroupLayout jPanelAvtaleLayout = new javax.swing.GroupLayout(jPanelAvtale);
        jPanelAvtale.setLayout(jPanelAvtaleLayout);
        jPanelAvtaleLayout.setHorizontalGroup(
            jPanelAvtaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvtaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAvtaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAvtale, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(jPanelAvtaleLayout.createSequentialGroup()
                        .addComponent(jLabelAvtale)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldAvtale, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelAvtaleBeskrivelse))
                .addContainerGap())
        );
        jPanelAvtaleLayout.setVerticalGroup(
            jPanelAvtaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAvtaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAvtaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAvtale)
                    .addComponent(jTextFieldAvtale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAvtaleBeskrivelse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAvtale, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDeltakere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jLabelDeltakere.setText("Deltakere:");

        jComboBoxDeltakerSok.setEditable(true);

        jButtonDeltakerLeggTil.setText("Legg til");

        jButtonDeltakerFjern.setText("Fjern");

        jScrollPaneDeltakere.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jScrollPaneDeltakere.setViewportView(jListDeltakere);

        javax.swing.GroupLayout jPanelDeltakereLayout = new javax.swing.GroupLayout(jPanelDeltakere);
        jPanelDeltakere.setLayout(jPanelDeltakereLayout);
        jPanelDeltakereLayout.setHorizontalGroup(
            jPanelDeltakereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDeltakereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeltakereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDeltakere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(jPanelDeltakereLayout.createSequentialGroup()
                        .addComponent(jLabelDeltakere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDeltakerSok, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeltakerLeggTil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeltakerFjern)))
                .addContainerGap())
        );
        jPanelDeltakereLayout.setVerticalGroup(
            jPanelDeltakereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeltakereLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDeltakereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeltakere)
                    .addComponent(jComboBoxDeltakerSok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeltakerFjern)
                    .addComponent(jButtonDeltakerLeggTil))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneDeltakere, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jLabelDato.setText("Dato: ");

        jTextFieldDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldDatoAction(evt);
            }
        });

        jLabelDatoStart.setText("Start:");

        jLabelDatoSlutt.setText("Slutt:");

        jTextFieldDatoStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldDatoStartAction(evt);
            }
        });

        jTextFieldDatoSlutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldDatoSluttAction(evt);
            }
        });

        jLabelVarighet.setText("Varighet:");

        jTextFieldVarighet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVarighetAction(evt);
            }
        });

        jButtonNesteMnd.setText("<");

        jButtonForrigeMnd.setText(">");
        jButtonForrigeMnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForrigeMndAction(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatoLayout = new javax.swing.GroupLayout(jPanelDato);
        jPanelDato.setLayout(jPanelDatoLayout);
        jPanelDatoLayout.setHorizontalGroup(
            jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoLayout.createSequentialGroup()
                .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatoLayout.createSequentialGroup()
                                .addComponent(jLabelDatoSlutt)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldDatoSlutt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addGroup(jPanelDatoLayout.createSequentialGroup()
                                .addComponent(jLabelDatoStart)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldDatoStart, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                            .addGroup(jPanelDatoLayout.createSequentialGroup()
                                .addComponent(jLabelDato)
                                .addGap(2, 2, 2)
                                .addComponent(jTextFieldDato, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatoLayout.createSequentialGroup()
                                .addComponent(jButtonNesteMnd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonForrigeMnd))
                            .addComponent(jXMonthViewDatovelger, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatoLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabelVarighet)
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldVarighet, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelDatoLayout.setVerticalGroup(
            jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatoLayout.createSequentialGroup()
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDato)
                            .addComponent(jTextFieldDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDatoStart)
                            .addComponent(jTextFieldDatoStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDatoSlutt)
                            .addComponent(jTextFieldDatoSlutt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDatoLayout.createSequentialGroup()
                        .addComponent(jXMonthViewDatovelger, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNesteMnd)
                            .addComponent(jButtonForrigeMnd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanelDatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVarighet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVarighet))
                .addContainerGap())
        );

        jButtonLagre.setText("Lagre");
        jButtonLagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLagreAction(evt);
            }
        });

        jButtonAvbryt.setText("Avbryt");
        jButtonAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvbrytAction(evt);
            }
        });

        jPanelRom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jLabelRom.setText("Rom:");

        jTextFieldRom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRomAction(evt);
            }
        });

        jLabelVelgRom.setText("Velg fra liste:");

        //TODO - add rooms
//        jListRom.setModel(new javax.swing.AbstractListModel() 
//        	{
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public Object getElementAt(int i) { return strings[i]; }
//        });
        jScrollPaneRom.setViewportView(jListRom);

        jRadioButtonRomAuto.setText("Velg automatisk");
        jRadioButtonRomAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRomAutoAction(evt);
            }
        });

        javax.swing.GroupLayout jPanelRomLayout = new javax.swing.GroupLayout(jPanelRom);
        jPanelRom.setLayout(jPanelRomLayout);
        jPanelRomLayout.setHorizontalGroup(
            jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneRom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRomLayout.createSequentialGroup()
                        .addComponent(jLabelRom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRom, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRomLayout.createSequentialGroup()
                        .addComponent(jLabelVelgRom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jRadioButtonRomAuto)))
                .addContainerGap())
        );
        jPanelRomLayout.setVerticalGroup(
            jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRom)
                    .addComponent(jTextFieldRom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVelgRom)
                    .addComponent(jRadioButtonRomAuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneRom, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAvbryt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLagre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelDeltakere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelAvtale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelRom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelAvtale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDeltakere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLagre)
                    .addComponent(jButtonAvbryt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonLagreAction(java.awt.event.ActionEvent evt) 
{
}

private void JTextFieldAvtaleAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldAvtaleAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldAvtaleAction

private void JTextFieldDatoAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldDatoAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldDatoAction

private void JTextFieldDatoStartAction(java.awt.event.ActionEvent evt) 
{//GEN-FIRST:event_JTextFieldDatoStartAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldDatoStartAction

private void JTextFieldDatoSluttAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldDatoSluttAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldDatoSluttAction

private void jTextFieldVarighetAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldVarighetAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldVarighetAction

private void jButtonForrigeMndAction(java.awt.event.ActionEvent evt) 
{
	Date date = new Date();
	date.setYear(2014);
	date.setMonth(4);
	date.setDate(14);
	jXMonthViewDatovelger.setSelectionDate(date);
	System.out.println(jXMonthViewDatovelger.getSelectionDate().getDate());
}

private void jTextFieldRomAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldRomAction
// TODO add your handling code here:
}//GEN-LAST:event_JTextFieldRomAction

private void jButtonAvbrytAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvbrytAction
main.setVisible(true);// TODO add your handling code here:
this.setVisible(false);

}//GEN-LAST:event_jButtonAvbrytAction

private void jRadioButtonRomAutoAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRomAutoAction
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonRomAutoAction

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLagre;
    private javax.swing.JButton jButtonAvbryt;
    private javax.swing.JButton jButtonNesteMnd;
    private javax.swing.JButton jButtonForrigeMnd;
    private javax.swing.JButton jButtonDeltakerLeggTil;
    private javax.swing.JButton jButtonDeltakerFjern;
    private javax.swing.JComboBox jComboBoxDeltakerSok;
    private javax.swing.JLabel jLabelAvtale;
    private javax.swing.JLabel jLabelAvtaleBeskrivelse;
    private javax.swing.JLabel jLabelRom;
    private javax.swing.JLabel jLabelVelgRom;
    private javax.swing.JLabel jLabelDato;
    private javax.swing.JLabel jLabelDatoStart;
    private javax.swing.JLabel jLabelDatoSlutt;
    private javax.swing.JLabel jLabelVarighet;
    private javax.swing.JLabel jLabelDeltakere;
    private javax.swing.JList jListRom;
    private javax.swing.JList jListDeltakere;
    private javax.swing.JPanel jPanelAvtale;
    private javax.swing.JPanel jPanelRom;
    private javax.swing.JPanel jPanelDeltakere;
    private javax.swing.JPanel jPanelDato;
    private javax.swing.JRadioButton jRadioButtonRomAuto;
    private javax.swing.JScrollPane jScrollPaneRom;
    private javax.swing.JScrollPane jScrollPaneAvtale;
    private javax.swing.JScrollPane jScrollPaneDeltakere;
    private javax.swing.JTextArea jTextAreaAvtale;
    private javax.swing.JTextField jTextFieldAvtale;
    private javax.swing.JTextField jTextFieldRom;
    private javax.swing.JTextField jTextFieldDato;
    private javax.swing.JTextField jTextFieldDatoStart;
    private javax.swing.JTextField jTextFieldDatoSlutt;
    private javax.swing.JTextField jTextFieldVarighet;
    private org.jdesktop.swingx.JXMonthView jXMonthViewDatovelger;
    // End of variables declaration//GEN-END:variables
}