package gruppe9.kalender.frontend;

import gruppe9.kalender.user.Bruker;

@SuppressWarnings("serial")
public class Main_Window extends javax.swing.JFrame {

    /** Creates new form Main_Window 
     * @param login_Window */
	private Login_Window login_Window;
    public Main_Window(Login_Window login_Window) 
    {
    	this.login_Window = login_Window;
        initComponents();
        tabWindow.addTab("Me", new Panel());
        tabWindow.addTab("Felles", new Panel());
        for (int x = 1; x<4; x++){
            tabWindow.addTab("Gruppe "+x, new Panel());
        }
        //System.out.println(this.Avtale_panel.getSize());
        //Avtale a = new Avtale();
        //Avtale_panel = a;
        //a.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabWindow = new javax.swing.JTabbedPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        kom_møte_list = new javax.swing.JList();
        kom_møte_label = new javax.swing.JLabel();
        uke_søk_field = new javax.swing.JTextField();
        forrige_button = new javax.swing.JButton();
        neste_button = new javax.swing.JButton();
        Avtale_panel = new javax.swing.JPanel();
        beskrivelse_label = new javax.swing.JLabel();
        deltakere_label = new javax.swing.JLabel();
        tidspunkt_label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deltaker_list = new javax.swing.JList();
        eier_label = new javax.swing.JLabel();
        avslå_choice = new javax.swing.JRadioButton();
        varsling_label = new javax.swing.JLabel();
        dato_label = new javax.swing.JLabel();
        varsel_valg_box = new javax.swing.JComboBox();
        avtale_label = new javax.swing.JLabel();
        kom_møte_label0 = new javax.swing.JLabel();
        delta_choice = new javax.swing.JRadioButton();
        rediger_button = new javax.swing.JButton();
        slett_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        beskrivelse_felt = new javax.swing.JTextArea();
        uke_label = new javax.swing.JLabel();
        top_panel = new javax.swing.JPanel();
        kom_møte_label1 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kom_møte_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(kom_møte_list);

        kom_møte_label.setText("Kommende Møter:");

        uke_søk_field.setText("Uke...");

        forrige_button.setFont(new java.awt.Font("Dialog", 1, 18));
        forrige_button.setText("<");

        neste_button.setFont(new java.awt.Font("Dialog", 1, 18));
        neste_button.setText(">");
        neste_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neste_buttonActionPerformed(evt);
            }
        });
        Avtale_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        beskrivelse_label.setText("Beskrivelse:");

        deltakere_label.setText("Deltakere");

        tidspunkt_label.setText("Tidspunkt:");

        deltaker_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Johanne", "Pedro", "Jesus", "McCain", "Fritz" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(deltaker_list);

        eier_label.setText("Eier:");

        avslå_choice.setText("Avslå ");
        avslå_choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avslå_choiceActionPerformed(evt);
            }
        });

        varsling_label.setText("Varsling:");

        dato_label.setText("Dato:");

        varsel_valg_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E-Mail", "Snail-Mail", "Trompet", "Alarm" }));

        avtale_label.setText("Avtale:");

        kom_møte_label0.setText("Endre:");

        delta_choice.setText("Delta");
        delta_choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delta_choiceActionPerformed(evt);
            }
        });

        rediger_button.setText("Rediger Avtale");
        rediger_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rediger_buttonActionPerformed(evt);
            }
        });

        slett_button.setText("Slett Avtale");
        slett_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slett_buttonActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        beskrivelse_felt.setColumns(20);
        beskrivelse_felt.setLineWrap(true);
        beskrivelse_felt.setRows(5);
        jScrollPane3.setViewportView(beskrivelse_felt);

        javax.swing.GroupLayout Avtale_panelLayout = new javax.swing.GroupLayout(Avtale_panel);
        Avtale_panel.setLayout(Avtale_panelLayout);
        Avtale_panelLayout.setHorizontalGroup(
            Avtale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avtale_panelLayout.createSequentialGroup()
                .addGroup(Avtale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Avtale_panelLayout.createSequentialGroup()
                        .addComponent(avtale_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(delta_choice)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avtale_panelLayout.createSequentialGroup()
                        .addContainerGap(185, Short.MAX_VALUE)
                        .addComponent(avslå_choice))
                    .addGroup(Avtale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(beskrivelse_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eier_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tidspunkt_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dato_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(deltakere_label)
                    .addComponent(varsling_label)
                    .addComponent(kom_møte_label0))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(varsel_valg_box, 0, 259, Short.MAX_VALUE)
            .addComponent(rediger_button, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(slett_button, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );
        Avtale_panelLayout.setVerticalGroup(
            Avtale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avtale_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Avtale_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delta_choice)
                    .addComponent(avtale_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avslå_choice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dato_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tidspunkt_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eier_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beskrivelse_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deltakere_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(varsling_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varsel_valg_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kom_møte_label0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rediger_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slett_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        uke_label.setText("UKE X  ");
        uke_label.setToolTipText("");
        uke_label.setAlignmentY(0.0F);

        top_panel.setForeground(new java.awt.Color(-1118482,true));

        kom_møte_label1.setFont(new java.awt.Font("SansSerif", 1, 12));
        kom_møte_label1.setText("Logget inn som " +Bruker.getUsername()+ ", PhD");

        logout_button.setText("Logg ut");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kom_møte_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 605, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addContainerGap())
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kom_møte_label1)
                    .addComponent(logout_button))
                .addGap(8, 8, 8))
        );

        jSeparator1.setForeground(new java.awt.Color(-10197916,true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(forrige_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kom_møte_label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabWindow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uke_søk_field, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(neste_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(Avtale_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(uke_label)
                .addContainerGap(610, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uke_søk_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(forrige_button)
                                                .addGap(41, 41, 41))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tabWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(kom_møte_label)
                                                .addGap(7, 7, 7)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(neste_button))))
                            .addComponent(uke_label))
                        .addGap(8, 8, 8))
                    .addComponent(Avtale_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void neste_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neste_buttonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_neste_buttonActionPerformed

private void avslå_choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avslå_choiceActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_avslå_choiceActionPerformed

private void delta_choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delta_choiceActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_delta_choiceActionPerformed

private void rediger_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rediger_buttonActionPerformed
// TODO add your handling code here:
    //REDIGER AVTALE
    Edit_Avtale a = new Edit_Avtale(this);
    a.setVisible(true);
    this.setVisible(false);
    a.setLocation(this.getLocation());
}//GEN-LAST:event_rediger_buttonActionPerformed

private void slett_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slett_buttonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_slett_buttonActionPerformed

private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_logout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forrige_button;
    private javax.swing.JButton neste_button;
    private javax.swing.JButton rediger_button;
    private javax.swing.JButton slett_button;
    private javax.swing.JButton logout_button;
    private javax.swing.JComboBox varsel_valg_box;
    private javax.swing.JLabel kom_møte_label;
    private javax.swing.JLabel kom_møte_label0;
    private javax.swing.JLabel kom_møte_label1;
    private javax.swing.JLabel uke_label;
    private javax.swing.JLabel tidspunkt_label;
    private javax.swing.JLabel eier_label;
    private javax.swing.JLabel beskrivelse_label;
    private javax.swing.JLabel deltakere_label;
    private javax.swing.JLabel varsling_label;
    private javax.swing.JLabel dato_label;
    private javax.swing.JLabel avtale_label;
    private javax.swing.JList kom_møte_list;
    private javax.swing.JList deltaker_list;
    private javax.swing.JPanel Avtale_panel;
    private javax.swing.JPanel top_panel;
    private javax.swing.JRadioButton delta_choice;
    private javax.swing.JRadioButton avslå_choice;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea beskrivelse_felt;
    private javax.swing.JTextField uke_søk_field;
    private javax.swing.JTabbedPane tabWindow;
    // End of variables declaration//GEN-END:variables
}
